//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  6 2018 12:02:43).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/Foundation.h>
#import "MSLayer.h"

@class MSStyle, NSString;

@interface _MSStyledLayer : MSLayer


+ (BOOL)allowsFaulting;

- (BOOL)hasDefaultValues;

@property(retain, nonatomic) MSStyle *style; // @synthesize style=_style;
@property(retain, nonatomic) NSString *sharedStyleID; // @synthesize sharedStyleID=_sharedStyleID;


@end

