//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  6 2018 12:02:43).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/Foundation.h>
#import "MSStyledLayer.h"

@class MSImageData;


@interface _MSTextLayer : MSStyledLayer
//{
//    MSAttributedString *_attributedString;
//    BOOL _automaticallyDrawOnUnderlyingPath;
//    BOOL _dontSynchroniseWithSymbol;
//    struct CGRect _glyphBounds;
//    long long _lineSpacingBehaviour;
//    MSImageData *_preview;
//    long long _textBehaviour;
//}

+ (BOOL)allowsFaulting;
+ (Class)immutableClass;



@property(retain, nonatomic) MSImageData *preview; // @synthesize preview=_preview;


//@property(retain, nonatomic) MSAttributedString *attributedString; // @synthesize attributedString=_attributedString;


@end

