//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  6 2018 12:02:43).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/Foundation.h>

@class MSPluginManagerWithActions;

@interface AppController : NSObject

+ (id)licenseAlertDateComponentsFormatter;
+ (id)templateLibraryURL;
+ (id)sharedInstance;
+ (void)initialize;

@property(retain, nonatomic) MSPluginManagerWithActions *pluginManager; // @synthesize pluginManager=_pluginManager;

@end

