//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  6 2018 12:02:43).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/Foundation.h>
#import <Cocoa/Cocoa.h>

@interface MSAbsoluteRect : NSObject

@property(nonatomic) CGPoint rulerOrigin;

@property(nonatomic) double rulerY;
@property(nonatomic) double rulerX;
- (void)setRect:(struct CGRect)arg1;
- (CGRect)rect;

- (double)height;

- (double)width;
- (double)y;
- (double)x;
//- (BOOL)boundsContainsPoint:(struct CGPoint)arg1;
//- (id)bezierBoundsInAbsoluteCoordinates;
//- (struct CGRect)absoluteRect;
//- (id)copyWithZone:(struct _NSZone *)arg1;
//- (void *)observationInfo;
//- (void)setObservationInfo:(void *)arg1;
//- (id)initWithLayer:(id)arg1;

@end

