//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  6 2018 12:02:43).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/Foundation.h>

@class MSSharedTextStyleContainer, MSSharedStyle;

@interface MSDocumentData : NSObject
- (id)allLayerStyles;
- (NSArray <MSSharedStyle *> *)allTextStyles;
@property(retain, nonatomic) MSSharedTextStyleContainer *layerTextStyles;
@property(retain, nonatomic) NSArray *pages;

- (id)allSymbols;
- (id)localSymbols;
- (id)allArtboards;
- (id)artboardWithID:(id)arg1;
- (id)layerWithID:(id)arg1;
- (void)layerTreeLayoutDidChange;
- (id)selectedLayers;
- (BOOL)documentIsEmpty;
- (id)nameForNewPage;
- (id)symbolsPageOrCreateIfNecessary;
- (id)symbolsPage;
- (id)addBlankPage;
- (void)removePages:(id)arg1 detachInstances:(BOOL)arg2;
@end

