//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  6 2018 12:02:43).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//


#import <Foundation/Foundation.h>


@interface MSImageData : NSObject <NSCopying>

+ (id)errorImage;

@property(retain, nonatomic) NSImage *image; // @synthesize image=_image;

- (id)NSImage;
@property(readonly, nonatomic) NSData *sha1;
@property(readonly, nonatomic) NSData *data;
- (void)waitForDataLock;
- (void)dealloc;
- (id)treeAsDictionary;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) Class superclass;

@end

