//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  6 2018 12:02:43).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/Foundation.h>

#import "_MSLayerGroup.h"

@class MSLayerArray;

@interface MSLayerGroup : _MSLayerGroup
{
    long long _preCalculatedHasSelectedLayer;
    unsigned long long _disableAutomaticScalingCounter;
}

// Deprecated from v53
+ (CGRect )groupBoundsForContainer:(MSLayerArray *)arg1;

+ (id)groupWithLayers:(id)arg1;
+ (id)groupWithLayer:(id)arg1;
- (CGRect)optimalBoundingBox;
- (CGRect)optimalBoundingBoxInParentCoordinates;
- (BOOL)fixGeometryWithOptions:(long long)arg1;

@end

