//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  6 2018 12:02:43).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/Foundation.h>
#import "_MSStyle.h"

//#import "MSSharedObjectInstance-Protocol.h"
//#import "NSCopying-Protocol.h"

@class MSTextStyle, NSString;

@interface MSStyle : _MSStyle <NSCopying>

@property(retain, nonatomic) NSString *primitiveSharedObjectID; // @synthesize primitiveSharedObjectID=_primitiveSharedObjectID;

@property(readonly, nonatomic) BOOL hasMarkers;
@property(readonly, nonatomic) double thickestStroke;
- (BOOL)hasTextStyle;
- (unsigned long long)type;
- (id)parentStyle;
- (id)parentLayer;


- (void)setTextStyle:(id)arg1;
//@property(retain, nonatomic) MSTextStyle *primitiveTextStyle;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

