//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  6 2018 12:02:43).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/Foundation.h>

@class MSColor;

@interface MSStyleFill : NSObject
{
}

+ (id)defaultStylePartForStyle:(id)arg1;
+ (id)defaultFillColor;
+ (id)keyPathsForValuesAffectingInterfaceOpacity;
@property(readonly, nonatomic) BOOL canReduceImageSize;
- (void)setReducedImage:(id)arg1;
@property(readonly, nonatomic) struct CGSize targetSizeForReduction;
- (id)NSImage;
- (void)setOpacity:(double)arg1;
- (BOOL)hasOpacity;
- (void)setPatternTileScale:(double)arg1;
- (void)performInitEmptyObject;
- (id)topViewForColorInspector:(id)arg1;
- (id)parentStyle;
@property(nonatomic) double interfaceOpacity;
- (void)configureFillForPreview:(id)arg1;
- (BOOL)hasEqualAppearance:(id)arg1;
- (id)CSSAttributeString;

@property(retain, nonatomic) MSColor *color; // @synthesize color=_color;

// Remaining properties
//@property(retain, nonatomic) MSImageData *image;

@end

