//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  6 2018 12:02:43).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//


#import <Foundation/Foundation.h>
#import "_MSTextLayer.h"

@class MSSharedTextStyleContainer;

@interface MSTextLayer : _MSTextLayer

@property(copy, nonatomic) NSString *stringValue;
@property(copy, nonatomic) NSAttributedString *attributedStringValue;
- (BOOL)isEmpty;
@property(copy, nonatomic) NSDictionary *styleAttributes;

+ (id)defaultValue;

- (id)sharedObject;

- (void)setStyle:(id)arg1;
- (id)PDFPreview;
- (void)addAttribute:(id)arg1 value:(id)arg2;
- (void)resetSharedStyle;
- (void)setSharedStyle:(id)arg1;
- (id)foreignSharedStyles;
- (void)adjustFrameToFit;
- (MSSharedTextStyleContainer *)styleContainer;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

